name: Maven Package

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      create_release:
        description: 'Tạo release kèm file .jar?'
        required: false
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Cần để tạo release và upload asset

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      # Tìm file .jar đầu ra
      - name: Locate JAR file
        id: locate_jar
        run: |
          JAR_PATH=$(find target -name "burp-recheck-scan*.jar" | head -n 1)
          echo "jar_file=$JAR_PATH" >> "$GITHUB_OUTPUT"

      - name: Create Release and Upload JAR
        if: github.event_name == 'workflow_dispatch' && inputs.create_release == 'true'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: manual-release-${{ github.run_number }}
          name: Manual Release ${{ github.run_number }}
          files: ${{ steps.locate_jar.outputs.jar_file }}
